### ISSUE TITLE
Exo Compte

### ISSUE THREAD

**Issue by sthiry2** [infradev4/exercice#2]
Tres bonne idée de mettre de l'heritage dans cette exo..

Je vous invite à faire la méthode Transferer qui est tres importante pour la comprehension de l'objet!

**Comment by infradev4** [comment]
J'ai ajouté la méthode transfert

**Comment by infradev4** [comment]
> 
> 
> Tres bonne idée de mettre de l'heritage dans cette exo..
> 
> Je vous invite à faire la méthode Transferer qui est tres importante pour la comprehension de l'objet!
